default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: localhost

development:
  adapter: postgresql
  encoding: utf8
  database: shootme-development
  pool: 5

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: shootme-test
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  database: shootme-prod
  pool: 5
  # username: shootme2
  # password: <%= ENV['shootme_database_password'] %>
