default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: localhost

development:
  adapter: sqlite3
  encoding: utf8
  database: db/development
  pool: 5

test: &TEST
  adapter: sqlite3
  encoding: utf8
  database: db/test
  pool: 5

production:
  adapter: sqlite3
  encoding: utf8
  database: db/shoot-me
  pool: 5
  username: shoot-me
  password: <%= ENV['SHOP-IT_DATABASE_PASSWORD'] %>
